server:
  port: 9999
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring
  application:
    name: eureka-1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  server:
    eviction-interval-timer-in-ms: 60000
    enable-self-preservation: false
logging:
  level:
    com.project：debug
