server:
  port: 7001
spring:
  application:
    name: eureka-1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka
  server:
    eviction-interval-timer-in-ms: 60000
    enable-self-preservation: false
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring-cloud.client.ip-address}:${spring.application.name}:${server.port}