#server:
#  port: 7777
#spring:
#  application:
#    name: sharding-jdbc-test
#  shardingsphere:
#    datasource:
#      names: m1,m2
#      m1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/order_db1?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#        username: root
#        password: 123456
#      m2:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/order_db2?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#        username: root
#        password: 123456
#    sharding:
#      tables:
#        t_order:
#          actual-data-nodes: m1.t_order$->{1..2}
#          key-generator:
#            column: id
#            type: SNOWFLAKE
#          table-strategy:
#            inline:
#              sharding-column: id #分片键
#              algorithm-expression: t_order$->{id % 2 +1} #分片路由表达式
#    props:
#      sql:
#        show: true
#logging:
#  level:
#    rooot: info
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka
#  instance:
#    hostname: ${spring.cloud.client.ip-address}
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}