server:
  port: 7008
spring:
  application:
    name: boot-apple
  thymeleaf:
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
feign:
  hystrix:
    enabled: true

autocoder:
  persist:
    entity: com.project.entity
    dao: com.project.mapper
logging:
  level:
     com.project.dao: debug

