server:
  port: 7777
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启自动路由,以服务id建立路由，服务id默认大写
      routes:
        - id: order-resources-route
          uri: bl://order-resources
          predicates:
            - Path=/api-order/**
          filters:
              # 添加请求路径的前缀
              #- PrefixPath=/user
              # 1表示过滤1个路径，2表示两个路径，以此类推
            - StripPrefix=1
        - id: stock-resources-route
          uri: bl://stock-resources
          predicates:
            - Path=/api-stock/**
          filters:
            - StripPrefix=1
        - id: login-resources-route
          uri: bl://login-resources
          predicates:
            - Path=/api-login/**
          filters:
            - StripPrefix=1
            - TokenVerify=token
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
token:
  invalid:
    ignored: /sign/*
