server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/longziyang/config-center.git
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#management:
#  endpoint:
#    web:
#      exposure:
#        # 暴露触发消息总线的地址
#        include: bus-refresh

